apiVersion: v1
appVersion: "0.1.0"
description: A Helm chart to deploy the Anexia CloudDNS cert-manager ACME solver webhook
name: cert-manager-webhook-anexia
version: 0.1.0
maintainers:
  - name: toothstone
    email: fzahn@anexia-it.com
